name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the hello-world Docker image
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
      run: |  
        docker build . --tag ghcr.io/Tadiesse/hello_docker:latest
        docker run ghcr.io/Tadiesse/hello_docker:latest
        docker push ghcr.io/Tadiesse/hello_docker:latest  