
name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      # - name: Install Cosign
      #   uses: sigstore/cosign-installer@main

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: 'Build Inventory Image'
        working-directory: ./
        run: |
          docker build . --tag ghcr.io/tadiesse/hello-docker:latest
          docker push ghcr.io/tadiesse/hello-docker:latest

      - name: cosign-installer
        # You may pin to the exact commit or the version.
        # uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19
        uses: sigstore/cosign-installer@main #v3.1.2


      
      # - name: Sign image with a key
      #   run: |
      #     cosign sign --yes --key env://COSIGN_PRIVATE_KEY -a "author=AlvinWorkingStudent"  ghcr.io/tadiesse/hello-docker:latest
      #   env:
      #     COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      #     COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

