
name: Deploy Images to GHCR

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   push-store-image:
#     runs-on: self-hosted
#     permissions:
#       contents: read
#       packages: write
#       id-token: write
#     steps:
#       - name: 'Checkout GitHub Action'
#         uses: actions/checkout@main
        
#       - name: Install cosign
#         if: github.event_name != 'pull_request'
#         uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 #v3.1.1
#         with:
#           cosign-release: 'v2.1.1'

on:
  schedule:
    - cron: '45 21 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: tadiesse/key_pair_signed


jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 #v3.1.1
        with:
          cosign-release: 'v2.1.1'




        
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: 'Build Inventory Image'
        working-directory: ./
        run: |
          docker build . --tag ghcr.io/tadiesse/hello-docker:latest
          docker push ghcr.io/tadiesse/hello-docker:latest
        
      - name: Sign image with a key
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY -a "author=AlvinWorkingStudent"  ghcr.io/tadiesse/hello-docker:latest
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

