name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: 'Build Inventory Image'
        working-directory: ./
        run: |
          docker build . --tag ghcr.io/tadiesse/hello-docker:latest
          docker push ghcr.io/tadiesse/hello-docker:latest

      - name: sign
        run: |
          cosign sign --yes --key C:\Users\z004rwpj\Documents\Alex_tasks\actions-runner\cosign.key ghcr.io/tadiesse/hello-docker@sha256:d06630f27b5fe95c0ab371dbc7c1d7d4cbefbcc08a21da175477f8ee76100fd1
      
      
      
      
          # $fileContent = Get-Content -Path C:\Users\z004rwpj\Documents\Alex_tasks\actions-runner\COSIGN_PASSWORD.txt
          # echo this the file content: $fileContent
          # echo this is the env variable from the host $env:cosign_env
          # # echo "fileContent=${{ env.fileContent }}" >> $GITHUB_ENV
          # # echo "cosign_env=${{ env.cosign_env }}" >> $GITHUB_ENV
      # - 
      #name: Sign image with a key
      #   run: cosign sign --yes --key C:\Users\z004rwpj\Downloads\cosign.key ghcr.io/tadiesse/hello-docker@sha256:d06630f27b5fe95c0ab371dbc7c1d7d4cbefbcc08a21da175477f8ee76100fd1        
        #echo this file content with ${{ env.fileContent }}
        #echo this is env variable with ${{ env.cosign_env }}
        #   echo "ok here is the file content: $file_content"
        #   echo "ok here is the cosign env: $cosign_env"
        # env:
        #   file_content: ${{ env.fileContent }}
        #   cosign_env: $env:cosign_env
          
        # env:
        #   COSIGN_PASSWORD:  ${{ env.fileContent }} #pwd123

      # - name: Run the command inputs
      #   run: |
      #     echo "the input variable is ${{ inputs.cosign_input }}"
      #     echo "ok here is the input: $input_Name"
      #   env:
      #     input_Name: ${{ inputs.cosign_input }}

      # - name: Install Cosign
      #   uses: sigstore/cosign-installer@main

      # - name: Read Text File Content
      #   id: read-file
      #   run: |
      #     # Read the content of your text file into a variable
      #     $fileContent = Get-Content -Path C:\Users\z004rwpj\Documents\Alex_tasks\actions-runner\COSIGN_PASSWORD.txt
      #     echo "::set-output name=fileContent::$fileContent"

      # - name: Set Environment Variable
      #   run: |
      #     # Set the environment variable with the file content
      #     echo "FILE_CONTENT=$env:fileContent" >> $GITHUB_ENV
          
      # - name: Verify Environment Variable
      #   run: |
      #     # Verify the environment variable is set
      #     echo "FILE_CONTENT: $FILE_CONTENT"


      # - name: Set the value
      #   run: |
      #     VAR=$env:VAR
      #     echo "Cosign Password: $VAR"

      # - name: cosign-installer
      #   uses: sigstore/cosign-installer@v3.1.2
      
      # - name: Sign image with a key
      #   run: |
      #     cosign sign --yes --key env://COSIGN_PRIVATE_KEY -a "author=AlvinWorkingStudent"  ghcr.io/tadiesse/hello-docker:latest
      #   env:
      #     COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      #     COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

